apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090 #http:/172.17.0.2:9090
    jsonData:
      timeInterval: 10s
      queryTimeout: 30s
      httpMethod: GET